/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Michael Zhang (https://sketchfab.com/beyond.zht)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/city-shanghai-sandboxie-3eab4438b9b34ceeaa35367429732970
title: City- Shanghai-Sandboxie
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/city.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-146830.08, -1040.32, -134780.73]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Shanghai-08-River_River_0'].geometry} material={materials.River} />
          </group>
          <group position={[-178116.28, -1293.06, -176341.41]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Shanghai-09-Floor_Floor_0'].geometry} material={materials.Floor} />
          </group>
          <group position={[-165720.94, 24065.21, -165337.83]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Shanghai-01_city_0'].geometry} material={materials.city} />
            <mesh geometry={nodes['Shanghai-01_city_0_1'].geometry} material={materials.city} />
            <mesh geometry={nodes['Shanghai-01_city_0_2'].geometry} material={materials.city} />
            <mesh geometry={nodes['Shanghai-01_city_0_3'].geometry} material={materials.city} />
            <mesh geometry={nodes['Shanghai-01_city_0_4'].geometry} material={materials.city} />
          </group>
          <group position={[-165720.94, 24065.21, -165337.83]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Shanghai-07_city_0'].geometry} material={materials.city} />
            <mesh geometry={nodes['Shanghai-07_city_0_1'].geometry} material={materials.city} />
          </group>
          <group position={[-165720.94, 24065.21, -165337.83]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['01-shanghaizhongxindasha_shanghaizhongxindasha_0'].geometry} material={materials.shanghaizhongxindasha} />
          </group>
          <group position={[-204696.34, 23692.12, -190750.67]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[38975.41, -25412.84, 373.09]}>
              <mesh geometry={nodes['04-dongfangmingzhu_dongfangmingzhu_0'].geometry} material={materials.dongfangmingzhu} />
            </group>
          </group>
          <group position={[-139712.63, 24542.02, -120065.73]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-26008.31, 45272.1, -476.8]}>
              <mesh geometry={nodes['02-huanqiujinrongzhongxin_huanqiujinrongzhongxin_0'].geometry} material={materials.huanqiujinrongzhongxin} />
            </group>
          </group>
          <group position={[-165720.94, 24065.21, -165337.83]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['03-jinmaodasha_jjinmaodasha_0'].geometry} material={materials.jjinmaodasha} />
          </group>
          <group position={[-184665.31, 7588.72, -304150.81]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[18944.38, -138812.98, 16476.49]}>
              <mesh geometry={nodes['Shanghai-06_city_0'].geometry} material={materials.city} />
              <mesh geometry={nodes['Shanghai-06_city_0_1'].geometry} material={materials.city} />
            </group>
          </group>
          <group position={[-165720.94, 24065.21, -165337.83]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Shanghai-05_city_0'].geometry} material={materials.city} />
            <mesh geometry={nodes['Shanghai-05_city_0_1'].geometry} material={materials.city} />
          </group>
          <group position={[-165720.94, 24065.21, -165337.83]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Shanghai-04_city_0'].geometry} material={materials.city} />
          </group>
          <group position={[-165720.94, 24065.21, -165337.83]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Shanghai-03_city_0'].geometry} material={materials.city} />
          </group>
          <group position={[-165720.94, 24065.21, -165337.83]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Shanghai-02_city_0'].geometry} material={materials.city} />
          </group>
          <group position={[-190590.75, 36095.59, 0]} rotation={[0, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.Text_text_0.geometry} material={materials.text} />
            <mesh geometry={nodes['Text_test-base_0'].geometry} material={materials['test-base']} />
          </group>
          <group position={[-164515.33, 24065.21, -168880.97]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object001_city_0.geometry} material={materials.city} />
          </group>
          <group position={[-162005.92, 24065.21, -155218.56]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object002_city_0.geometry} material={materials.city} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/city.gltf')
