/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: limyankaidarryl (https://sketchfab.com/limyankaidarryl)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/world-map-static-0eedf0e3ebfe4bec9ea6e86b92068024
title: World Map Static
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/map.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.2}>
        <group rotation={[Math.PI / 2, 0, 0]}  scale={0.1}>
          <group position={[171.34, -43.85, 10]}>
            <mesh geometry={nodes.Cap_1_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Cap_2_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Extrude_mat_green_0.geometry} material={materials.mat_green} />
          </group>
          <group position={[159.28, -51.59, 10]}>
            <mesh geometry={nodes.Cap_1_2_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Cap_2_2_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Extrude_1_mat_green_0.geometry} material={materials.mat_green} />
          </group>
          <group position={[235.06, -27.31, 10]}>
            <mesh geometry={nodes.Cap_1_3_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Cap_2_3_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Extrude_2_mat_green_0.geometry} material={materials.mat_green} />
          </group>
          <group position={[222.79, -103.42, 10]}>
            <mesh geometry={nodes.Cap_1_4_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Cap_2_4_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Extrude_3_mat_green_0.geometry} material={materials.mat_green} />
          </group>
          <group position={[209.45, 59.29, 10]}>
            <mesh geometry={nodes.Cap_1_5_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Cap_2_5_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Extrude_4_mat_green_0.geometry} material={materials.mat_green} />
          </group>
          <group position={[213.77, 73.97, 10]}>
            <mesh geometry={nodes.Cap_1_6_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Cap_2_6_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Extrude_5_mat_green_0.geometry} material={materials.mat_green} />
          </group>
          <group position={[202.44, -35.55, 10]}>
            <mesh geometry={nodes.Cap_1_7_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Cap_2_7_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Extrude_6_mat_green_0.geometry} material={materials.mat_green} />
          </group>
          <group position={[197.06, -14.53, 10]}>
            <mesh geometry={nodes.Cap_1_8_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Cap_2_8_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Extrude_7_mat_green_0.geometry} material={materials.mat_green} />
          </group>
          <group position={[194.65, -22.32, 10]}>
            <mesh geometry={nodes.Cap_1_9_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Cap_2_9_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Extrude_8_mat_green_0.geometry} material={materials.mat_green} />
          </group>
          <group position={[191.63, -36.61, 10]}>
            <mesh geometry={nodes.Cap_1_10_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Cap_2_10_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Extrude_9_mat_green_0.geometry} material={materials.mat_green} />
          </group>
          <group position={[186.92, -34.14, 10]}>
            <mesh geometry={nodes.Cap_1_11_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Cap_2_11_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Extrude_10_mat_green_0.geometry} material={materials.mat_green} />
          </group>
          <group position={[211.64, -67.94, 10]}>
            <mesh geometry={nodes.Cap_1_12_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Cap_2_12_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Extrude_11_mat_green_0.geometry} material={materials.mat_green} />
          </group>
          <group position={[172.57, -31.12, 10]}>
            <mesh geometry={nodes.Cap_1_13_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Cap_2_13_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Extrude_12_mat_green_0.geometry} material={materials.mat_green} />
          </group>
          <group position={[180.36, -12.79, 10]}>
            <mesh geometry={nodes.Cap_1_14_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Cap_2_14_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Extrude_13_mat_green_0.geometry} material={materials.mat_green} />
          </group>
          <group position={[153.63, -16.32, 10]}>
            <mesh geometry={nodes.Cap_1_15_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Cap_2_15_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Extrude_14_mat_green_0.geometry} material={materials.mat_green} />
          </group>
          <group position={[112.26, 0.27, 10]}>
            <mesh geometry={nodes.Cap_1_16_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Cap_2_16_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Extrude_15_mat_green_0.geometry} material={materials.mat_green} />
          </group>
          <group position={[41.92, -55.56, 10]}>
            <mesh geometry={nodes.Cap_1_17_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Cap_2_17_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Extrude_16_mat_green_0.geometry} material={materials.mat_green} />
          </group>
          <group position={[78.35, 24.65, 10]}>
            <mesh geometry={nodes.Cap_1_18_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Cap_2_18_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Extrude_17_mat_green_0.geometry} material={materials.mat_green} />
          </group>
          <group position={[-53.19, 96.84, 10]}>
            <mesh geometry={nodes.Cap_1_19_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Cap_2_19_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Extrude_18_mat_green_0.geometry} material={materials.mat_green} />
          </group>
          <group position={[-63.45, 94.6, 10]}>
            <mesh geometry={nodes.Cap_1_20_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Cap_2_20_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Extrude_19_mat_green_0.geometry} material={materials.mat_green} />
          </group>
          <group position={[-198.58, 1.22, 10]}>
            <mesh geometry={nodes.Cap_1_21_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Cap_2_21_mat_green_0.geometry} material={materials.mat_green} />
            <mesh geometry={nodes.Extrude_20_mat_green_0.geometry} material={materials.mat_green} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/map.gltf')
