/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: lololol (https://sketchfab.com/conganh0110)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/solar-system-122e4b0e9ded461a842568bad0127ac7
title: Solar System
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/solar.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={0.2}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group>
              <group>
                <group position={[7.24, 0, 9.63]} rotation={[0, 0.58, 0]} scale={0.28}>
                  <mesh geometry={nodes.mercury_lambert1_0.geometry} material={materials.lambert1} />
                </group>
                <group position={[-13.11, 0, 4.56]} rotation={[0, -1.17, 0]} scale={0.28}>
                  <mesh geometry={nodes.venus_lambert1_0.geometry} material={materials.lambert1} />
                </group>
                <group position={[-12.45, 0, -8.64]} rotation={[-Math.PI, -0.88, -Math.PI]} scale={0.47}>
                  <mesh geometry={nodes.earth_lambert1_0.geometry} material={materials.lambert1} />
                </group>
                <group position={[-7.19, 0, -13.44]} rotation={[-Math.PI, -0.36, -Math.PI]} scale={0.19}>
                  <mesh geometry={nodes.mars_lambert1_0.geometry} material={materials.lambert1} />
                </group>
                <group position={[8.68, 0, 18.5]} rotation={[0, 0.17, 0]} scale={1.1}>
                  <mesh geometry={nodes.jupiter_lambert1_0.geometry} material={materials.lambert1} />
                </group>
                <group position={[-24.53, 0, 3.1]} rotation={[0, -1.38, 0]}>
                  <mesh geometry={nodes.saturn1_lambert1_0.geometry} material={materials.lambert1} />
                </group>
                <group position={[39.95, 0, 19.8]} rotation={[0, 0.5, 0]} scale={0.39}>
                  <mesh geometry={nodes.neptune_lambert1_0.geometry} material={materials.lambert1} />
                </group>
                <group name="uranus" position={[-32.71, 0, 18.05]} rotation={[0, -0.75, 0]} scale={0.4}>
                  <mesh geometry={nodes.uranus_lambert1_0.geometry} material={materials.lambert1} />
                </group>
                <group rotation={[0, 1.48, 0]} scale={5.1}>
                  <mesh geometry={nodes.sun_lambert1_0.geometry} material={materials.lambert1} />
                </group>
                
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/solar.gltf')
